### ISSUE TITLE
Fix for OTP 18

### ISSUE THREAD

**Issue by dmilith** [potatosalad/lftpc#1]
lftpc.erl:131:

change:
now()

to:

erlang:timestamp()

**Comment by potatosalad** [comment]
This should be fixed in version [1.0.4](https://github.com/potatosalad/lftpc/tree/1.0.4).  Let me know if you have any other issues.

**Comment by dmilith** [comment]
Nope, excepta that everything looks/ compiles just fine :)

**Comment by dmilith** [comment]
When accessing from Elixir (mix) i still see (for v1.0.4 of lftpc):

```
Compiling src/lftpc.erl failed:
src/lftpc.erl:131: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
ERROR: compile failed while processing /Projects/ost/deps/lftpc: rebar_abort
==> ost
** (Mix) Could not compile dependency lftpc, /Users/dmilith/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile lftpc
```

**Comment by dmilith** [comment]
This is how I set dependency in mix.exs:

```
{:lftpc, github: "potatosalad/lftpc", tag: "v1.0.4"}
```

**Comment by potatosalad** [comment]
Whoops, rebar.config needed to have a `platform_define` which would force it to switch to `erlang:timestamp/0` on OTP >= 18.

**Comment by potatosalad** [comment]
Version [1.0.5](https://github.com/potatosalad/lftpc/tree/1.0.5) should work now.

Also, make sure to use `1.0.5` instead of `v1.0.5` when defining the mix dependency:

```elixir
{:lftpc, github: "potatosalad/lftpc", tag: "1.0.5"}
```

**Comment by dmilith** [comment]
Confirmed, works fine. Thank you!
